var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "yyyyMMdd",
            "fulldayshow": "yyyy年M月d日",
            "fulldayvalue": "yyyy-M-d",
            "Md": "M/d (W)",
            "Md3": "M月d日",
            "separator": "-",
            "year_index": 0,
            "month_index": 1,
            "day_index": 2,
            "day": "d日",
            "sun": "週日",
            "mon": "週一",
            "tue": "週二",
            "wed": "週三",
            "thu": "週四",
            "fri": "週五",
            "sat": "週六",
            "jan": "一月",
            "feb": "二月",
            "mar": "三月",
            "apr": "四月",
            "may": "五月",
            "jun": "六月",
            "jul": "七月",
            "aug": "八月",
            "sep": "�?月",
            "oct": "�??月",
            "nov": "�??一月",
            "dec": "�??二月"
        },
        "no_implemented": "沒有實�?�",
        "to_date_view": "點擊轉到該日期的日視圖",
        "i_undefined": "未設置",
        "allday_event": "全天日程",
        "repeat_event": "跨天日程",
        "time": "時 間",
        "event": "事 件",
        "location": "地 點",
        "participant": "�?�與人",
        "get_data_exception": "�?��?�數據發生異常",
        "new_event": "新日程",
        "confirm_delete_event": "確定刪除該日程嗎？",
        "confrim_delete_event_or_all": "刪除此�?列還是單個事件？\r\n點擊[確定]刪除事件,點擊[�?�消]刪除�?列",
        "data_format_error": "數據格�?錯誤�?",
        "invalid_title": "日程標題�?能為空且�?能包�?�符號($<>)",
        "view_no_ready": "視圖未準備就緒",
        "example": "例如：有個辦公會議",
        "content": "內 容",
        "create_event": "創建日程",
        "update_detail": "修改日程詳細信�?�",
        "click_to_detail": "點擊查看詳細",
        "i_delete": "刪除",
        "day_plural": "天",
        "others": "�?�外",
        "item": "個"
    }
}); 