CREATE TABLE IF NOT EXISTS `eligibility_payer_list` (
  `payer_list_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `change` char(1) DEFAULT NULL,
  `payer_names` varchar(250) DEFAULT NULL,
  `payer_ids` varchar(20) DEFAULT NULL,
  `model` varchar(20) DEFAULT NULL,
  `lob` varchar(20) DEFAULT NULL,
  `trans_type` varchar(100) DEFAULT NULL,
  `enroll` char(1) DEFAULT NULL,
  `npi` char(1) DEFAULT NULL,
  `link` char(1) DEFAULT NULL,
  `5010` char(1) DEFAULT NULL,
  `additional_information` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`payer_list_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

DROP TABLE IF EXISTS `eligibility_service_type`;
CREATE TABLE `eligibility_service_type` (
  `service_type_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `service_type_code` char(2) DEFAULT NULL,
  `description` varchar(250) DEFAULT NULL,
  `response_returned` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`service_type_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `eligibility_service_type` (`service_type_id`, `service_type_code`, `description`, `response_returned`) VALUES
(1, '1', 'Medical Care', 'See Service Type Code 30'),
(2, '2', 'Surgical', 'Surgery, Inpatient, Outpatient, Office or SPU.; also includes Routine Surgeries performed in the office by specialists or PCPs'),
(3, '3', 'Consultation', 'Consultations'),
(4, '4', 'Diagnostic X-ray', 'X-rays, Office or Outpatient, including Bone Mass Measurement and Mammograms'),
(5, '5', 'Diagnostic Lab', 'Outpatient or Office Lab. Also includes Colorectal, Prostate and Pap Smear Screenings'),
(6, '6', 'Radiation Therapy', 'Radiation Therapy, Facility Outpatient or SPU as well as Specialist Office Visit'),
(7, '7', 'Anesthesia', 'See Service Type Code 30'),
(8, '8', 'Surgical Assistance', 'Assistant Surgeon - Inpatient'),
(9, '9', 'Other Medical', 'Walk-in clinic visits and eVisits when included in the plan. If not included, will return active coverage only.'),
(10, '10', 'Blood Charges', 'Blood Charges, Inpatient or Outpatient'),
(11, '11', 'Used Durable Medical Equipment', 'See Service Type Code 30'),
(12, '12', 'Durable Medical Equipment Purchase', 'Durable Medical Equipment'),
(13, '13', 'Ambulatory Service Center Facility', 'Outpatient, SPU or Ambulatory Surgical Facility'),
(14, '14', 'Renal Supplies in the Home', 'See Service Type Code 30'),
(15, '15', 'Alternate Method Dialysis', 'See Service Type Code 30'),
(16, '16', 'Chronic Renal Disease (CRD) Equipment', 'See Service Type Code 30'),
(17, '17', 'Preadmission Testing', 'Preadmission Testing, Outpatient, Office or SPU'),
(18, '18', 'Durable Medical Equipment Rental', 'Durable Medical Equipment'),
(19, '19', 'Pneumonia Vaccine', 'See Service Type Code 30'),
(20, '20', 'Second Surgical Opinion', 'Second Surgical Opinion'),
(21, '21', 'Third Surgical Opinion', 'See Service Type Code 30'),
(22, '22', 'Social Work', 'See Service Type Code 30'),
(23, '23', 'Diagnostic Dental', 'Diagnostic Dental'),
(24, '24', 'Periodontics', 'Periodontics'),
(25, '25', 'Restorative', 'Restorative'),
(26, '26', 'Endodontics', 'Endodontics'),
(27, '27', 'Maxillofacial Prosthetics', 'Prosthetics'),
(28, '28', 'Adjunctive Dental Services', 'Palliative Treatment'),
(29, '30', 'Health Benefit Plan Coverage', 'Includes STCs 1, 33, 35, 47, 86, 88, 98, AL, MH, UC (1, 35, 47, 88 only return active coverage response) - only covered STCs will be returned'),
(30, '32', 'Plan Waiting Period', 'See Service Type Code 30'),
(31, '33', 'Chiropractic', 'Chiropractic Office Visits and Manipulations'),
(32, '34', 'Chiropractic Office Visits', 'Chiropractic Office Visits and Manipulations'),
(33, '35', 'Dental Care', 'Service Types 23, 24, 25, 26, 27, 28, 37, 38, 39, 40, 41 as of August 2010. Only covered STCs will be returned.'),
(34, '36', 'Dental Crowns', 'Crowns'),
(35, '37', 'Dental Accident', 'Active Coverage Response'),
(36, '38', 'Orthodontics', 'Orthodontics'),
(37, '39', 'Prosthodontics', 'Prosthodontics'),
(38, '40', 'Oral Surgery', 'Oral Surgery'),
(39, '41', 'Routine (Preventive) Dental', 'Prophylaxis'),
(40, '42', 'Home Health Care', 'Home Health Visits and Infusion Therapy'),
(41, '43', 'Home Health Prescriptions', 'See Service Type Code 30'),
(42, '44', 'Home Health Visits', 'Home Health Visits and Infusion Therapy'),
(43, '45', 'Hospice', 'Hospice, Inpatient and Outpatient'),
(44, '46', 'Respite Care', 'See Service Type Code 30'),
(45, '47', 'Hospital', '48, 49, 50, 51, 52, 53 as of August 2010. Only covered STCs will be returned.'),
(46, '48', 'Hospital - Inpatient', 'Inpatient Hospital'),
(47, '49', 'Hospital - Room and Board', 'See Service Type Code 30'),
(48, '50', 'Hospital - Outpatient', 'Outpatient Hospital including Outpatient Surgery'),
(49, '51', 'Hospital - Emergency Accident', 'Emergency Room, including Accident'),
(50, '52', 'Hospital - Emergency Medical', 'Emergency Room, including Urgent Care'),
(51, '53', 'Hospital - Ambulatory Surgical', 'Outpatient Hospital, specifically Ambulatory Surgery'),
(52, '54', 'Long Term Care', 'See Service Type Code 30'),
(53, '55', 'Major Medical', 'See Service Type Code 30'),
(54, '56', 'Medically Related Transportation', 'See Service Type Code 30'),
(55, '57', 'Air Transportation', 'Air Ambulance'),
(56, '58', 'Ambulance', 'See Service Type Code 30'),
(57, '59', 'Licensed Ambulance', 'Ground Ambulance'),
(58, '60', 'General Benefits', 'Hospital Emergency, Hospital Diagnostic X-ray/Lab, Physician Office, including PCP and Specialist Office Visit and Consultations. Benefits returned for the same services as 50, 73, 98 - returned using STC60'),
(59, '61', 'In-vitro Fertilization', 'Invitro Fertilization and Artificial Inseminiation'),
(60, '62', 'MRI/CAT Scan', 'Complex Imaging'),
(61, '63', 'Donor Procedures', 'See Service Type Code 30'),
(62, '64', 'Acupuncture', 'See Service Type Code 30'),
(63, '65', 'Newborn Care', 'Well Baby Care including Inpatient Newborn Care'),
(64, '66', 'Pathology', 'Diagnostic Pathology'),
(65, '67', 'Smoking Cessation', 'See Service Type Code 30'),
(66, '68', 'Well Baby Care', 'Well Baby Care'),
(67, '69', 'Maternity', 'Maternity Care including Normal Vaginal Delivery, Caesarean and Maternity Room and Board'),
(68, '70', 'Transplants', 'See Service Type Code 30'),
(69, '71', 'Audiology Exam', 'See Service Type Code 30'),
(70, '72', 'Inhalation Therapy', 'See Service Type Code 30'),
(71, '73', 'Diagnostic Medical', 'Diagnostic Medical including X-ray, Lab and Mammograms'),
(72, '74', 'Private Duty Nursing', 'Private Duty Nursing'),
(73, '75', 'Prosthetic Device', 'Prosthetics'),
(74, '76', 'Dialysis', 'Renal Dialysis'),
(75, '77', 'Otological Exam', 'See Service Type Code 30'),
(76, '78', 'Chemotherapy', 'Chemo Therapy and Chemo Injectable Medications'),
(77, '79', 'Allergy Testing', 'Allergy Testing'),
(78, '80', 'Immunizations', 'Immunizations including adult and child immunizations and flu vaccinations'),
(79, '81', 'Routine Physical', 'Routine Physical Exams including Well-Woman exams and Hearing Exams'),
(80, '82', 'Family Planning', 'Family Planning, which includes Voluntary Sterilization (Tubal Ligation and Vasectomy)'),
(81, '83', 'Infertility', 'Infertility treatments including Artificial Insemination'),
(82, '84', 'Abortion', 'Abortion including elective abortions'),
(83, '85', 'AIDS', 'See Service Type Code 30'),
(84, '86', 'Emergency Services', 'Emergency Services including Urgent Care'),
(85, '87', 'Cancer', 'See Service Type Code 30'),
(86, '88', 'Pharmacy', 'Active Coverage Response'),
(87, '89', 'Free Standing Prescription Drug', 'Active Coverage Response'),
(88, '90', 'Mail Order Prescription Drug', 'Active Coverage Response'),
(89, '91', 'Brand Name Prescription Drug', 'Active Coverage Response'),
(90, '92', 'Generic Prescription Drug', 'Active Coverage Response'),
(91, '93', 'Podiatry', 'Consultations'),
(92, '94', 'Podiatry - Office Visits', 'Consultations'),
(93, '95', 'Podiatry - Nursing Home Visits', 'See Service Type Code 30'),
(94, '96', 'Professional (Physician)', 'See Service Type Code 30'),
(95, '97', 'Anesthesiologist', 'Anesthesia, including Inpatient and Office'),
(96, '98', 'Professional (Physician) Visit - Office', 'Office Visits including PCPs and Specialists'),
(97, '99', 'Professional (Physician) Visit - Inpatient', 'Inpatient Physician Visits'),
(98, 'A0', 'Professional (Physician) Visit - Outpatient', 'Outpatient Physician Visits'),
(99, 'A1', 'Professional (Physician) Visit - Nursing Home', 'Nursing Home Physician Visits'),
(100, 'A2', 'Professional (Physician) Visit - Skilled Nursing Facility', 'Skilled Nursing Facility Physician Visits'),
(101, 'A3', 'Professional (Physician) Visit - Home', 'See Service Type Code 30'),
(102, 'A4', 'Psychiatric', 'Outpatient Psychiatric Services'),
(103, 'A5', 'Psychiatric - Room and Board', 'See Service Type Code 30'),
(104, 'A6', 'Psychotherapy', 'Outpatient Psychotherapy Services including Drug and Alcohol Treatments'),
(105, 'A7', 'Psychiatric - Inpatient', 'Inpatient Psychiatric Services including Drug and Alcohol Treatments'),
(106, 'A8', 'Psychiatric - Outpatient', 'Outpatient Psychiatric Services'),
(107, 'A9', 'Rehabilitation', 'See Service Type Code 30'),
(108, 'AA', 'Rehabilitation - Room and Board', 'See Service Type Code 30'),
(109, 'AB', 'Rehabilitation - Inpatient', 'Inpatient Physical Rehabilitation Services'),
(110, 'AC', 'Rehabilitation - Outpatient', 'Outpatient Physical Rehabilitation Services'),
(111, 'AD', 'Occupational Therapy', 'Occupational Therapy by MD, DO or Non-Physician'),
(112, 'AE', 'Physical Medicine', 'Physical Medicine Services by MD, DO or Non-Physician'),
(113, 'AF', 'Speech Therapy', 'Speech Therapy by Physician or Therapist'),
(114, 'AG', 'Skilled Nursing Care', 'Skilled Nursing Facility'),
(115, 'AH', 'Skilled Nursing Care - Room and Board', 'Skilled Nursing Facility'),
(116, 'AI', 'Substance Abuse', 'Substance Abuse Treatment including Drug and Alcohol Abuse'),
(117, 'AJ', 'Alcoholism', 'See Service Type Code 30'),
(118, 'AK', 'Drug Addiction', 'See Service Type Code 30'),
(119, 'AL', 'Vision (Optometry)', 'Routine Vision, including Eye Exam, Lenses and Frames'),
(120, 'AM', 'Frames', 'Vision- Frames'),
(121, 'AN', 'Routine Exam', 'Routine Vision, including Eye Exam, Lenses and Frames'),
(122, 'AO', 'Lenses', 'Vision- Lenses'),
(123, 'AQ', 'Non-Medically Necessary Physical', 'See Service Type Code 30'),
(124, 'AR', 'Experimental Drug Therapy', 'See Service Type Code 30'),
(125, 'B1', 'Burn Care', 'See Service Type Code 30'),
(126, 'B2', 'Brand Name Prescription Drug - Formulary', 'Active Coverage Response'),
(127, 'B3', 'Brand Name Prescription Drug - Non-Formulary', 'Active Coverage Response'),
(128, 'BA', 'Independent Medical Evaluation', 'See Service Type Code 30'),
(129, 'BB', 'Partial Hospitalization (Psychiatric)', 'See Service Type Code 30'),
(130, 'BC', 'Day Care (Psychiatric)', 'See Service Type Code 30'),
(131, 'BD', 'Cognitive Therapy', 'See Service Type Code 30'),
(132, 'BE', 'Massage Therapy', 'See Service Type Code 30'),
(133, 'BF', 'Pulmonary Rehabilitation', 'See Service Type Code 30'),
(134, 'BG', 'Cardiac Rehabilitation', 'Cardiac Rehab Outpatient Facility'),
(135, 'BH', 'Pediatric', 'Well Child Care'),
(136, 'BI', 'Nursery', 'See Service Type Code 30'),
(137, 'BJ', 'Skin', 'See Service Type Code 30'),
(138, 'BK', 'Orthopedic', 'See Service Type Code 30'),
(139, 'BL', 'Cardiac', 'See Service Type Code 30'),
(140, 'BM', 'Lymphatic', 'See Service Type Code 30'),
(141, 'BN', 'Gastrointestinal', 'See Service Type Code 30'),
(142, 'BP', 'Endocrine', 'See Service Type Code 30'),
(143, 'BQ', 'Neurology', 'See Service Type Code 30'),
(144, 'BR', 'Eye', 'See Service Type Code 30'),
(145, 'BS', 'Invasive Procedures', 'See Service Type Code 30'),
(146, 'BT', 'Gynecological', 'Well Woman Exam including Pap Smear'),
(147, 'BU', 'Obstetrical', 'Maternity Care including Normal Vaginal Delivery, Caesarean and Maternity Room and Board'),
(148, 'BV', 'Obstetrical/Gynecological', 'Maternity Care including Normal Vaginal Delivery, Caesarean and Maternity Room and Board as well as Well Woman Exam including Pap Smear'),
(149, 'BW', 'Mail Order Prescription Drug: Brand Name', 'Active Coverage Response'),
(150, 'BX', 'Mail Order Prescription Drug: Generic', 'Active Coverage Response'),
(151, 'BY', 'Physician Visit - Office: Sick', 'Physician Office Visit PCP or Specialist'),
(152, 'BZ', 'Physician Visit - Office: Well', 'Well Adult or Child Care'),
(153, 'C1', 'Coronary Care', 'See Service Type Code 30'),
(154, 'CA', 'Private Duty Nursing - Inpatient', 'Private Duty Nursing'),
(155, 'CB', 'Private Duty Nursing - Home', 'Private Duty Nursing'),
(156, 'CC', 'Surgical Benefits - Professional (Physician)', 'Surgery, Inpatient, Outpatient and Office; also includes Routine Surgeries performed in the office by Specialists or PCPs'),
(157, 'CD', 'Surgical Benefits - Facility', 'Surgery, Inpatient, Outpatient, Office and SPU; also includes Routine Surgeries performed in the office by Specialists or PCPs'),
(158, 'CE', 'Mental Health Provider - Inpatient', 'Detail'),
(159, 'CF', 'Mental Health Provider - Outpatient', 'Outpatient Psychiatric Services'),
(160, 'CG', 'Mental Health Facility - Inpatient', 'Inpatient Psychiatric Services'),
(161, 'CH', 'Mental Health Facility - Outpatient', 'Outpatient Psychiatric Services'),
(162, 'CI', 'Substance Abuse Facility - Inpatient', 'Substance Abuse, Inpatient - including Drug and Alcohol'),
(163, 'CJ', 'Substance Abuse Facility - Outpatient', 'Substance Abuse, Outpatient - including Drug and Alcohol'),
(164, 'CK', 'Screening X-ray', 'Screening X-ray including Routine X-rays and Mammograms'),
(165, 'CL', 'Screening Laboratory', 'Screening Laboratory Services'),
(166, 'CM', 'Mammogram, High Risk Patient', 'Mammograms'),
(167, 'CN', 'Mammogram, Low Risk Patient', 'Mammograms'),
(168, 'CO', 'Flu Vaccination', 'Flu Vaccinations'),
(169, 'CP', 'Eyewear and Eyewear Accessories', 'Routine Vision, including Eye Exam, Lenses and Frames'),
(170, 'CQ', 'Case Management', 'See Service Type Code 30'),
(171, 'DG', 'Dermatology', 'Office Visit and Office Surgery'),
(172, 'DM', 'Durable Medical Equipment', 'Durable Medical Equipment'),
(173, 'DS', 'Diabetic Supplies', 'Diabetic Supplies'),
(174, 'GF', 'Generic Prescription Drug - Formulary', 'Active Coverage Response'),
(175, 'GN', 'Generic Prescription Drug - Non-Formulary', 'Active Coverage Response'),
(176, 'GY', 'Allergy', 'Allergy Testing, Allergy Serum and Allergy Injections'),
(177, 'IC', 'Intensive Care', 'Intensive Care Room and Board'),
(178, 'MH', 'Mental Health', 'Facility Inpatient and Outpatient Mental Health'),
(179, 'NI', 'Neonatal Intensive Care', 'Neonatal Intensive Care'),
(180, 'ON', 'Oncology', 'Oncology Office Visit and Chemo Services including Chemo Injectable Medication'),
(181, 'PT', 'Physical Therapy', 'Physical Therapy'),
(182, 'PU', 'Pulmonary', 'Consultation'),
(183, 'RN', 'Renal', 'Renal Dialysis'),
(184, 'RT', 'Residential Psychiatric Treatment', 'Residential Psychiatric Treatment'),
(185, 'TC', 'Transitional Care', 'See Service Type Code 30'),
(186, 'TN', 'Transitional Nursery Care', 'See Service Type Code 30'),
(187, 'UC', 'Urgent Care', 'Urgent Care Services');


ALTER TABLE `practice_settings` ADD `eligiblity_host` VARCHAR( 255 ) NULL DEFAULT NULL AFTER `dosepot_singlesignon_clinickey`;
ALTER TABLE `practice_settings` ADD `eligiblity_username` VARCHAR( 255 ) NULL DEFAULT NULL AFTER `eligiblity_host`;
ALTER TABLE `practice_settings` ADD `eligiblity_password` VARCHAR( 255 ) NULL DEFAULT NULL AFTER `eligiblity_username`;
ALTER TABLE `practice_settings` ADD `eligiblity_sender_id` VARCHAR( 255 ) NULL DEFAULT NULL AFTER `eligiblity_password`;
ALTER TABLE `practice_settings` ADD `eligiblity_receiver_id` VARCHAR( 255 ) NULL DEFAULT NULL AFTER `eligiblity_sender_id`;
